server:
  port: 8080

# database 연동 설정
spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
#    각자 PC에 만들어놓은 Database이름을 써야 합니다.
    url: jdbc:mysql://localhost:3306/member?serverTimezone=UTC&characterEncoding=UTF-8
#    mysql에 생성한 사용자 계정 정보를 써야 합니다.
    username: root
    password: 1229
  thymeleaf:
    cache: false

  # spring data jpa 설정
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    open-in-view: false
    show-sql: true
    format_sql: true

upload:
  dir: "C:/Users/dlaco/Desktop/Capstone_Project/Back_End/src/main/resources/static/photos"


logging:
  level:
    org:
      hibernate: DEBUG