server:
  port: 8080

# database 연동 설정
spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
#    각자 PC에 만들어놓은 Database이름을 써야 합니다.
    url: jdbc:mysql://localhost:3306/member?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
#    mysql에 생성한 사용자 계정 정보를 써야 합니다.
    username: root
    password: 1229
  thymeleaf:
    cache: false

upload:
  dir: "C:/Users/dlaco/Desktop/캡스톤 프로젝트/Back_End/src/main/resources/static/photos/postPhoto"

  # spring data jpa 설정
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    open-in-view: false
    show-sql: true
    format_sql: true
    hibernate:
      ddl-auto: update

logging:
  level:
    org:
      hibernate: DEBUG